#!/usr/bin/perl

use strict;
use warnings;
use File::Slurp qw(read_file write_file);

my @types = (
	# [qw(Char char)],
	[qw(Integer int)],
	[qw(Long long)],
	[qw(Float float)],
	[qw(Double double)],
);

my $transform = read_file('ShortArrayTransform.java');
my $converter = read_file('ShortArrayConverter.java');

for my $type (@types) {

	{
		my $code = $transform;
		$code =~ s/Short/$type->[0]/g;
		$code =~ s/short/$type->[1]/g;
		$code =~ s/parseInteger/parseInt/g;
		$code =~ s/Integers/Ints/g;
		$code = "// AUTOGENERATED from ShortArray{Converter,Transform}.java\n$code";

		my $name = $type->[0] . 'ArrayTransform.java';
		write_file($name, $code);
	}

	{
		my $code = $converter;
		$code =~ s/Short/$type->[0]/g;
		$code =~ s/short/$type->[1]/g;
		$code = "// AUTOGENERATED from ShortArrayConverter.java\n$code";

		my $name = $type->[0] . 'ArrayConverter.java';
		write_file($name, $code);
	}
}
